### ISSUE TITLE
can you release the data used in the paper

### ISSUE THREAD

**Issue by HarshaSatyavardhan** [zjuKeLiu/PCVAE#1]

**Comment by zjuKeLiu** [comment]
Hi, thanks for your interest in this work. We have released the code and datasets in the latest commit, and you can find the dataset in on my google drive, the link of which can be found at the folder data.

**Comment by HarshaSatyavardhan** [comment]
the drive is asking for permission request to download the data can you give access. Thanks

**Comment by zjuKeLiu** [comment]
> the drive is asking for permission request to download the data can you give access. Thanks

I have changed the restriction and the datasets can be downloaded now. Please try again.
